# Generated by Django 4.2.1 on 2023-06-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="car_id",
            new_name="bike_id",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="car_title",
            new_name="bike_title",
        ),
    ]
