# Generated by Django 4.2.1 on 2023-05-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0004_alter_car_features_alter_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
